# Generated by Django 3.0.5 on 2020-04-19 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_auto_20200419_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_admin', models.CharField(max_length=100)),
                ('name_to_show', models.CharField(max_length=100)),
                ('image_to_show', models.ImageField(upload_to='images/')),
                ('available', models.BooleanField(default=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Gender')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
