# Generated by Django 3.0.5 on 2020-04-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_to_show',
            field=models.ImageField(upload_to='categories/'),
        ),
    ]
