# Generated by Django 3.0.5 on 2020-04-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_to_show', models.CharField(max_length=100)),
                ('image_to_show', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
