# Generated by Django 3.0.5 on 2020-04-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genders',
            new_name='Gender',
        ),
    ]
