# Generated by Django 3.0.5 on 2020-04-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20200419_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='image_to_show',
            field=models.ImageField(upload_to='people/'),
        ),
    ]
